### PR TITLE
new interface

### PR DESCRIPTION
**Pull request by alexeyneu**

### CODE REVIEW

**Comment by alexeyneu** [comment]
COM model is c++ itself. And you just have no chances to understand C++ to C transition in near future

**Comment by alexeyneu** [comment]
script fixed

**Comment by sindresorhus** [comment]
Sorry @alexeyneu, but #5 was almost done by the time you submitted this, and I also don't think it improves the readability much. You're add somewhat simpler syntax, but also a *lot* of boilerplate. If I were to simplify it, I would rather rewrite it in Rust than C++, TBH.

**Comment by alexeyneu** [comment]
C code you see is generated by MIDL . C++ is native for COM

**Pull request closed without merging**
