### PR TITLE
fix bug with variable

### PR DESCRIPTION
**Pull request by theuves**

### CODE REVIEW

**Comment by sindresorhus** [comment]
What exactly is the bug here?

**Comment by theuves** [comment]
In fact this is a mistake when compiling, because of the variable repetition "i" (at least I think that's it).

Look:



The version of my `gcc` is 4.9.2

**Comment by sindresorhus** [comment]
// @Qix-

**Comment by Qix-** [comment]
Need to add `-std=c99`. That, or update your version of GCC.

**Comment by theuves** [comment]
@Qix- Thank you, it worked.

**Pull request closed without merging**
